require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/users", type: :request do
  let(:valid_attributes) {
    {
      "name" => "Agung Wijaya",
      "email" => "agung@gmail.com",
      "password" => "password",
      "username" => "agung-w",
    }
  }


  let(:invalid_attributes) {
    user=build(:user,email:"agung@gmail")
    user.as_json
  }

  describe "POST /email-login" do
    context "with valid parameters" do
      it "return login information (token.)" do
        create(:user)
        post login_email_url, params: { user: valid_attributes }
        expect(response).to have_http_status(:ok)
      end
    end

    context "with invalid parameters" do
      it "return error message and its status code" do
        create(:user,email:"agung1@gmail.com")
        post login_email_url, params: { user: valid_attributes }
        expect(response).to have_http_status(:unauthorized)
      end
    end
  end

  describe "POST /email-registration" do
    context "with valid parameters" do
      it "creates a new user" do
        expect{
          post register_email_url, params: { user: valid_attributes }
        }.to change(User, :count).by(1)
        expect(User.first.username).to eq("agung-w")
      end
      it "only accept name, email, password, and username params" do
        expect{
          post register_email_url, params: { user: 
            {
              "name" => "Agung Wijaya",
              "email" => "agung@gmail.com",
              "password" => "password",
              "username" => "agung-w",
            } 
          }
        }.to change(User, :count).by(1)
        expect(User.first.username).to eq("agung-w")
        expect(User.first.followers_count).to eq(0)
      end
      it "still create user and generate default username if username not given" do
        expect{
          post register_email_url, params: { user: 
            {
              "name" => "Agung Wijaya",
              "email" => "agung@gmail.com",
              "password" => "password",
            } 
          }
        }.to change(User, :count).by(1)
        expect(User.first.username).to eq("user_00000001")
        expect(User.first.followers_count).to eq(0)
      end
    end


    context "with invalid parameters" do
      it "does not create a new User" do
        expect {
          post register_email_url, params: { user: invalid_attributes }
        }.to change(User, :count).by(0)
      end
    end

    context "with registered email" do
      it "does not create a new User" do
        create(:user)
        expect {
          post register_email_url, params: { user: valid_attributes }
        }.to change(User, :count).by(0)
      end
    end
  end

  describe "GET /profile" do
    context "with valid parameters" do
      it "return profile details" do
        user=create(:user)
        get profile_url(username: user.username )
        expect(response).to have_http_status(:ok)
      end
    end
    context "with invalid parameters" do
      it "return error message" do
        user=create(:user)
        get profile_url(username: user.username*2 )
        expect(response).to have_http_status(:not_found)
      end
    end
  end

  describe "GET /my-profile" do
    context "with valid parameters" do
      it "return profile details" do
        user=create(:user)
        headers = {
          "Content-Type": "application/json",
          "Authorization": "Bearer #{ENV['TEST_TOKEN']}", 
        }
        get my_profile_url, :headers => headers
        expect(response).to have_http_status(:ok)
      end
    end
    context "with invalid parameters" do
      it "return error message" do
        user=create(:user)
        get my_profile_url
        expect(response).to have_http_status(:unauthorized)
      end
    end
  end
end
